//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/GameplayInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameplayInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameplayInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameplayInputs"",
    ""maps"": [
        {
            ""name"": ""Boat"",
            ""id"": ""be6c4bf5-cce8-4353-ac99-d5a013e6256a"",
            ""actions"": [
                {
                    ""name"": ""PaddleLeft"",
                    ""type"": ""Value"",
                    ""id"": ""ec7d4462-88fd-4f43-8928-11e27232ea53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PaddleRight"",
                    ""type"": ""Value"",
                    ""id"": ""90c3aca1-1a2b-4b05-a9a6-0ecf98f6952b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StaticRotateLeft"",
                    ""type"": ""Value"",
                    ""id"": ""31fcf997-f244-4d71-9596-0801daf74d3f"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StaticRotateRight"",
                    ""type"": ""Value"",
                    ""id"": ""68f74b2f-e772-4377-9710-58135b74f550"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ResetCamera"",
                    ""type"": ""Value"",
                    ""id"": ""ab86d594-21ec-40bb-8ec8-749b64f9654a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""94bc673f-e28e-491d-987f-4e04c7c7dbad"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DialogSkip"",
                    ""type"": ""Button"",
                    ""id"": ""5d09007b-cbc8-4cd4-a8f0-4eed24b01a10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenWheelMenu"",
                    ""type"": ""Value"",
                    ""id"": ""3897178e-d8e5-42d2-b1c6-075428adc16c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectOnWheelX"",
                    ""type"": ""Value"",
                    ""id"": ""41104c3d-e5eb-4b95-9d70-09869384b221"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectOnWheelY"",
                    ""type"": ""Value"",
                    ""id"": ""4cf84e59-5e02-4d3a-88d7-3f4822ef8b4f"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeselectWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""3df5f837-8436-4878-9be5-2f58a701ed96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Value"",
                    ""id"": ""e8cecd45-fe58-4e62-880c-2d553338bee1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveAim"",
                    ""type"": ""Value"",
                    ""id"": ""6d1491e7-7ca5-413c-9386-98053f453c4b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Value"",
                    ""id"": ""7057980f-4ac7-41c6-a33c-ea6ca6e9401e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UnbalancedRight"",
                    ""type"": ""Button"",
                    ""id"": ""536c1b49-1bbd-4281-94e8-66356b26c49c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnbalancedLeft"",
                    ""type"": ""Button"",
                    ""id"": ""825655f2-9165-416b-a147-181bd2009188"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowPauseMenus"",
                    ""type"": ""Button"",
                    ""id"": ""e412642b-f162-4c33-9f57-0efea12c64c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenuUp"",
                    ""type"": ""Button"",
                    ""id"": ""32572d08-52fc-40bf-aae4-ec14ab9564d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenuDown"",
                    ""type"": ""Button"",
                    ""id"": ""d0d92bef-1600-401f-9ba7-e7beb25a860e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenuLeft"",
                    ""type"": ""Button"",
                    ""id"": ""97b135d6-f8df-431f-93a3-31745bd76226"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenuRight"",
                    ""type"": ""Button"",
                    ""id"": ""7cb7aa46-ea7d-4221-8288-a0d70a7d9623"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenuTopLeft"",
                    ""type"": ""Button"",
                    ""id"": ""812d2664-a5e6-46cb-a2bb-110f327173d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenuTopRight"",
                    ""type"": ""Button"",
                    ""id"": ""c967f5ea-3c02-4d98-bf19-51d86d2a89b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ParameterMenuPressButton"",
                    ""type"": ""Button"",
                    ""id"": ""c51ba526-eb6c-4664-a10d-a7ef60efa205"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClosePauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""f48ba92a-5447-4450-a90e-df13a3299c44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AnyButton"",
                    ""type"": ""Button"",
                    ""id"": ""b3be2c60-e795-4356-be41-3ca008864ecb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowLeaveMenu"",
                    ""type"": ""Button"",
                    ""id"": ""6002375a-62e0-4484-8344-9e95513a061c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3cfa1491-41a9-4ca7-a280-5a43d52d446e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""PaddleLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecc743e3-3393-43b9-8bb9-fc74b1d7df00"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""PaddleLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84d99ad0-1484-4aab-991c-2d9fa37ffddc"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""PaddleRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""552cac4e-9249-4cbe-9e57-4af35a458181"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""PaddleRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98e456ff-58ef-4d20-bd85-6f2f8c69cc97"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""StaticRotateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9080299f-91ab-47cf-883d-fb860410a663"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""StaticRotateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62a3c127-3f1f-4b5a-9e99-e4c86b6c0755"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""StaticRotateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ef8087e-4505-4945-aeb6-aff821b2bc0b"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""StaticRotateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e987401-15f1-4c58-8252-74271067c81b"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false)"",
                    ""groups"": ""GamePad"",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1b4b7b8-9fe4-428b-84be-cf322c633df0"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""ResetCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4c9b76c-690c-4ebf-8821-dd3443904c8f"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""ResetCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""499f5e8e-ee4b-43ea-bb48-fd3c9f4d6d4b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""DialogSkip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46354184-2a3e-4b3f-a67f-fef2bb867f03"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""DialogSkip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f43ca2a-d8b2-442e-bf39-32832d7c4143"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""OpenWheelMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7fa617b-1ea1-4ae8-831d-a0f69de7ae94"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""OpenWheelMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f65d129-1c19-4806-aa4d-dc91c9bd8998"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""SelectOnWheelX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2fc37d0-a769-4043-aed1-6719ec9c1bcf"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""DeselectWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a0281f8-918b-4947-bfbc-3050167498f4"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""DeselectWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4672f842-d893-4358-8095-fc96aa2b4492"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8583a4d7-eb25-49b8-9fec-64b882d52bc5"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b782da75-3bc2-4af1-928a-9a0947ee8542"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc51c2ad-af2e-40ca-be76-584bc7d914fd"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc693c8b-5880-425f-86fc-1b9a97e8014d"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c5181f8-75d8-4536-a0a7-ae0ef4a05301"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d8d0ac4-d8c4-4be2-ac02-0f4af55d9156"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""UnbalancedRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45417cfa-9acf-4c1a-ad21-61e31c9a33fb"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""UnbalancedRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7e15cc8-3a1e-4c6f-8f2c-18357324baa4"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""UnbalancedLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3c2823d-dd45-4011-ad57-742a574d5ac6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""UnbalancedLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b8fdf28-c343-4bca-b5d3-32eceed31fd4"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowPauseMenus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61722d3b-ca01-4c19-a1d2-ce562465d3e7"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowPauseMenus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70f8d796-3b28-4082-baaa-e4a5ad02c3b0"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f65ae569-0a24-40fe-a54c-486e34ce0cc7"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9d56c93-7348-4084-bebe-01eb6f71b00d"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93e532f7-e741-40fd-beaa-4d93972f630b"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bfaa056-ae4f-4713-856c-1e7712383560"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""496d96ef-2382-4037-a1b6-88e1dad9e1c9"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b705fbb6-4778-4196-a983-c8e7f4a1d29c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80776b60-1483-46a1-bf90-19d949d1b942"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83e88186-8ec1-464b-966c-b62fbfa47c63"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa3bbf62-0d3d-4d0d-8816-b87ba48287f9"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54e25fb1-583f-4a41-92f5-4c5de01119a8"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94af1272-ce3e-4ec3-9e2f-80d67cd79add"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4bbbc98-9eaa-4836-8c7e-50b86738d4af"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuTopLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60ee1704-d819-4b0f-9471-d72ed70e8f52"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuTopLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a2a0128-529b-4689-a9e2-6e3305987a31"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuTopRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f3e40a0-3827-42f4-9632-c0a127353ee8"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuTopRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06e60e77-78f9-47c8-b653-2c2dfcf16f99"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""SelectOnWheelY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a788e16-c3c3-4f2d-8f3b-0b641fd7c728"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""ParameterMenuPressButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""700ff9aa-49ba-4225-9969-223b9d322881"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""ParameterMenuPressButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f4b7ad8-800c-4c04-87da-2b3dd3799b34"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""ClosePauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b68a0eb7-af81-45d6-9b19-835631d26b93"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""ClosePauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dee4e71-f509-4925-9891-c1e3d4c1481b"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb925449-d034-4472-aa46-2802020f0195"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d37dfde2-4e46-41a8-83d4-6ca8b1875790"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b24a0c3b-1182-464e-91ba-a316c3e19f8d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59e80cec-44e8-41b2-8d23-09968a57195c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""708abcc1-67dd-401b-9053-aed3ee764be1"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25d1c613-2589-4294-bd01-146957eb1740"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7363c46-23eb-4604-bfbf-2301c4562d81"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36697f02-c518-43f4-883c-14b4613c77f4"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18926ef6-9253-4a58-a31b-f6b84a5d03aa"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88c59786-78d1-4d05-af76-63f8bc9ae923"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2586fc0c-d44c-419c-b08a-38843a043393"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1abba791-f0b2-453c-9431-acecdd1f56a7"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4f7afb1-765d-4cec-98e9-327ca8b0f522"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29b1a08b-94a9-46bb-8b80-0234ae5a642c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60252cbd-46f5-4a66-9b10-0c9278b85146"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b0a8787-d871-40fa-9099-be313bc3d54c"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac37bca4-147e-4668-ad7d-8707d582c7bc"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e36b726e-a042-45b1-9fbe-ba86ec0c7005"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8ae0d82-c867-4c13-9a03-f9b32d9dc4e1"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d4f3d27-641e-4225-8414-3b71eafb6814"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowLeaveMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59d4a217-f89e-41f0-a155-8a34ab73b324"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""ShowLeaveMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardMouse"",
            ""bindingGroup"": ""KeyboardMouse"",
            ""devices"": []
        },
        {
            ""name"": ""GamePad"",
            ""bindingGroup"": ""GamePad"",
            ""devices"": []
        }
    ]
}");
        // Boat
        m_Boat = asset.FindActionMap("Boat", throwIfNotFound: true);
        m_Boat_PaddleLeft = m_Boat.FindAction("PaddleLeft", throwIfNotFound: true);
        m_Boat_PaddleRight = m_Boat.FindAction("PaddleRight", throwIfNotFound: true);
        m_Boat_StaticRotateLeft = m_Boat.FindAction("StaticRotateLeft", throwIfNotFound: true);
        m_Boat_StaticRotateRight = m_Boat.FindAction("StaticRotateRight", throwIfNotFound: true);
        m_Boat_ResetCamera = m_Boat.FindAction("ResetCamera", throwIfNotFound: true);
        m_Boat_RotateCamera = m_Boat.FindAction("RotateCamera", throwIfNotFound: true);
        m_Boat_DialogSkip = m_Boat.FindAction("DialogSkip", throwIfNotFound: true);
        m_Boat_OpenWheelMenu = m_Boat.FindAction("OpenWheelMenu", throwIfNotFound: true);
        m_Boat_SelectOnWheelX = m_Boat.FindAction("SelectOnWheelX", throwIfNotFound: true);
        m_Boat_SelectOnWheelY = m_Boat.FindAction("SelectOnWheelY", throwIfNotFound: true);
        m_Boat_DeselectWeapon = m_Boat.FindAction("DeselectWeapon", throwIfNotFound: true);
        m_Boat_Aim = m_Boat.FindAction("Aim", throwIfNotFound: true);
        m_Boat_MoveAim = m_Boat.FindAction("MoveAim", throwIfNotFound: true);
        m_Boat_Shoot = m_Boat.FindAction("Shoot", throwIfNotFound: true);
        m_Boat_UnbalancedRight = m_Boat.FindAction("UnbalancedRight", throwIfNotFound: true);
        m_Boat_UnbalancedLeft = m_Boat.FindAction("UnbalancedLeft", throwIfNotFound: true);
        m_Boat_ShowPauseMenus = m_Boat.FindAction("ShowPauseMenus", throwIfNotFound: true);
        m_Boat_MenuUp = m_Boat.FindAction("MenuUp", throwIfNotFound: true);
        m_Boat_MenuDown = m_Boat.FindAction("MenuDown", throwIfNotFound: true);
        m_Boat_MenuLeft = m_Boat.FindAction("MenuLeft", throwIfNotFound: true);
        m_Boat_MenuRight = m_Boat.FindAction("MenuRight", throwIfNotFound: true);
        m_Boat_MenuTopLeft = m_Boat.FindAction("MenuTopLeft", throwIfNotFound: true);
        m_Boat_MenuTopRight = m_Boat.FindAction("MenuTopRight", throwIfNotFound: true);
        m_Boat_ParameterMenuPressButton = m_Boat.FindAction("ParameterMenuPressButton", throwIfNotFound: true);
        m_Boat_ClosePauseMenu = m_Boat.FindAction("ClosePauseMenu", throwIfNotFound: true);
        m_Boat_AnyButton = m_Boat.FindAction("AnyButton", throwIfNotFound: true);
        m_Boat_ShowLeaveMenu = m_Boat.FindAction("ShowLeaveMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Boat
    private readonly InputActionMap m_Boat;
    private IBoatActions m_BoatActionsCallbackInterface;
    private readonly InputAction m_Boat_PaddleLeft;
    private readonly InputAction m_Boat_PaddleRight;
    private readonly InputAction m_Boat_StaticRotateLeft;
    private readonly InputAction m_Boat_StaticRotateRight;
    private readonly InputAction m_Boat_ResetCamera;
    private readonly InputAction m_Boat_RotateCamera;
    private readonly InputAction m_Boat_DialogSkip;
    private readonly InputAction m_Boat_OpenWheelMenu;
    private readonly InputAction m_Boat_SelectOnWheelX;
    private readonly InputAction m_Boat_SelectOnWheelY;
    private readonly InputAction m_Boat_DeselectWeapon;
    private readonly InputAction m_Boat_Aim;
    private readonly InputAction m_Boat_MoveAim;
    private readonly InputAction m_Boat_Shoot;
    private readonly InputAction m_Boat_UnbalancedRight;
    private readonly InputAction m_Boat_UnbalancedLeft;
    private readonly InputAction m_Boat_ShowPauseMenus;
    private readonly InputAction m_Boat_MenuUp;
    private readonly InputAction m_Boat_MenuDown;
    private readonly InputAction m_Boat_MenuLeft;
    private readonly InputAction m_Boat_MenuRight;
    private readonly InputAction m_Boat_MenuTopLeft;
    private readonly InputAction m_Boat_MenuTopRight;
    private readonly InputAction m_Boat_ParameterMenuPressButton;
    private readonly InputAction m_Boat_ClosePauseMenu;
    private readonly InputAction m_Boat_AnyButton;
    private readonly InputAction m_Boat_ShowLeaveMenu;
    public struct BoatActions
    {
        private @GameplayInputs m_Wrapper;
        public BoatActions(@GameplayInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @PaddleLeft => m_Wrapper.m_Boat_PaddleLeft;
        public InputAction @PaddleRight => m_Wrapper.m_Boat_PaddleRight;
        public InputAction @StaticRotateLeft => m_Wrapper.m_Boat_StaticRotateLeft;
        public InputAction @StaticRotateRight => m_Wrapper.m_Boat_StaticRotateRight;
        public InputAction @ResetCamera => m_Wrapper.m_Boat_ResetCamera;
        public InputAction @RotateCamera => m_Wrapper.m_Boat_RotateCamera;
        public InputAction @DialogSkip => m_Wrapper.m_Boat_DialogSkip;
        public InputAction @OpenWheelMenu => m_Wrapper.m_Boat_OpenWheelMenu;
        public InputAction @SelectOnWheelX => m_Wrapper.m_Boat_SelectOnWheelX;
        public InputAction @SelectOnWheelY => m_Wrapper.m_Boat_SelectOnWheelY;
        public InputAction @DeselectWeapon => m_Wrapper.m_Boat_DeselectWeapon;
        public InputAction @Aim => m_Wrapper.m_Boat_Aim;
        public InputAction @MoveAim => m_Wrapper.m_Boat_MoveAim;
        public InputAction @Shoot => m_Wrapper.m_Boat_Shoot;
        public InputAction @UnbalancedRight => m_Wrapper.m_Boat_UnbalancedRight;
        public InputAction @UnbalancedLeft => m_Wrapper.m_Boat_UnbalancedLeft;
        public InputAction @ShowPauseMenus => m_Wrapper.m_Boat_ShowPauseMenus;
        public InputAction @MenuUp => m_Wrapper.m_Boat_MenuUp;
        public InputAction @MenuDown => m_Wrapper.m_Boat_MenuDown;
        public InputAction @MenuLeft => m_Wrapper.m_Boat_MenuLeft;
        public InputAction @MenuRight => m_Wrapper.m_Boat_MenuRight;
        public InputAction @MenuTopLeft => m_Wrapper.m_Boat_MenuTopLeft;
        public InputAction @MenuTopRight => m_Wrapper.m_Boat_MenuTopRight;
        public InputAction @ParameterMenuPressButton => m_Wrapper.m_Boat_ParameterMenuPressButton;
        public InputAction @ClosePauseMenu => m_Wrapper.m_Boat_ClosePauseMenu;
        public InputAction @AnyButton => m_Wrapper.m_Boat_AnyButton;
        public InputAction @ShowLeaveMenu => m_Wrapper.m_Boat_ShowLeaveMenu;
        public InputActionMap Get() { return m_Wrapper.m_Boat; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BoatActions set) { return set.Get(); }
        public void SetCallbacks(IBoatActions instance)
        {
            if (m_Wrapper.m_BoatActionsCallbackInterface != null)
            {
                @PaddleLeft.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnPaddleLeft;
                @PaddleLeft.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnPaddleLeft;
                @PaddleLeft.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnPaddleLeft;
                @PaddleRight.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnPaddleRight;
                @PaddleRight.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnPaddleRight;
                @PaddleRight.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnPaddleRight;
                @StaticRotateLeft.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnStaticRotateLeft;
                @StaticRotateLeft.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnStaticRotateLeft;
                @StaticRotateLeft.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnStaticRotateLeft;
                @StaticRotateRight.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnStaticRotateRight;
                @StaticRotateRight.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnStaticRotateRight;
                @StaticRotateRight.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnStaticRotateRight;
                @ResetCamera.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnResetCamera;
                @ResetCamera.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnResetCamera;
                @ResetCamera.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnResetCamera;
                @RotateCamera.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnRotateCamera;
                @DialogSkip.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnDialogSkip;
                @DialogSkip.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnDialogSkip;
                @DialogSkip.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnDialogSkip;
                @OpenWheelMenu.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnOpenWheelMenu;
                @OpenWheelMenu.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnOpenWheelMenu;
                @OpenWheelMenu.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnOpenWheelMenu;
                @SelectOnWheelX.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnSelectOnWheelX;
                @SelectOnWheelX.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnSelectOnWheelX;
                @SelectOnWheelX.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnSelectOnWheelX;
                @SelectOnWheelY.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnSelectOnWheelY;
                @SelectOnWheelY.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnSelectOnWheelY;
                @SelectOnWheelY.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnSelectOnWheelY;
                @DeselectWeapon.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnDeselectWeapon;
                @DeselectWeapon.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnDeselectWeapon;
                @DeselectWeapon.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnDeselectWeapon;
                @Aim.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnAim;
                @MoveAim.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnMoveAim;
                @MoveAim.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnMoveAim;
                @MoveAim.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnMoveAim;
                @Shoot.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnShoot;
                @UnbalancedRight.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnUnbalancedRight;
                @UnbalancedRight.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnUnbalancedRight;
                @UnbalancedRight.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnUnbalancedRight;
                @UnbalancedLeft.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnUnbalancedLeft;
                @UnbalancedLeft.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnUnbalancedLeft;
                @UnbalancedLeft.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnUnbalancedLeft;
                @ShowPauseMenus.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnShowPauseMenus;
                @ShowPauseMenus.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnShowPauseMenus;
                @ShowPauseMenus.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnShowPauseMenus;
                @MenuUp.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuUp;
                @MenuUp.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuUp;
                @MenuUp.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuUp;
                @MenuDown.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuDown;
                @MenuDown.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuDown;
                @MenuDown.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuDown;
                @MenuLeft.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuLeft;
                @MenuLeft.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuLeft;
                @MenuLeft.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuLeft;
                @MenuRight.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuRight;
                @MenuRight.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuRight;
                @MenuRight.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuRight;
                @MenuTopLeft.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuTopLeft;
                @MenuTopLeft.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuTopLeft;
                @MenuTopLeft.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuTopLeft;
                @MenuTopRight.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuTopRight;
                @MenuTopRight.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuTopRight;
                @MenuTopRight.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnMenuTopRight;
                @ParameterMenuPressButton.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnParameterMenuPressButton;
                @ParameterMenuPressButton.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnParameterMenuPressButton;
                @ParameterMenuPressButton.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnParameterMenuPressButton;
                @ClosePauseMenu.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnClosePauseMenu;
                @ClosePauseMenu.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnClosePauseMenu;
                @ClosePauseMenu.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnClosePauseMenu;
                @AnyButton.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnAnyButton;
                @AnyButton.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnAnyButton;
                @AnyButton.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnAnyButton;
                @ShowLeaveMenu.started -= m_Wrapper.m_BoatActionsCallbackInterface.OnShowLeaveMenu;
                @ShowLeaveMenu.performed -= m_Wrapper.m_BoatActionsCallbackInterface.OnShowLeaveMenu;
                @ShowLeaveMenu.canceled -= m_Wrapper.m_BoatActionsCallbackInterface.OnShowLeaveMenu;
            }
            m_Wrapper.m_BoatActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PaddleLeft.started += instance.OnPaddleLeft;
                @PaddleLeft.performed += instance.OnPaddleLeft;
                @PaddleLeft.canceled += instance.OnPaddleLeft;
                @PaddleRight.started += instance.OnPaddleRight;
                @PaddleRight.performed += instance.OnPaddleRight;
                @PaddleRight.canceled += instance.OnPaddleRight;
                @StaticRotateLeft.started += instance.OnStaticRotateLeft;
                @StaticRotateLeft.performed += instance.OnStaticRotateLeft;
                @StaticRotateLeft.canceled += instance.OnStaticRotateLeft;
                @StaticRotateRight.started += instance.OnStaticRotateRight;
                @StaticRotateRight.performed += instance.OnStaticRotateRight;
                @StaticRotateRight.canceled += instance.OnStaticRotateRight;
                @ResetCamera.started += instance.OnResetCamera;
                @ResetCamera.performed += instance.OnResetCamera;
                @ResetCamera.canceled += instance.OnResetCamera;
                @RotateCamera.started += instance.OnRotateCamera;
                @RotateCamera.performed += instance.OnRotateCamera;
                @RotateCamera.canceled += instance.OnRotateCamera;
                @DialogSkip.started += instance.OnDialogSkip;
                @DialogSkip.performed += instance.OnDialogSkip;
                @DialogSkip.canceled += instance.OnDialogSkip;
                @OpenWheelMenu.started += instance.OnOpenWheelMenu;
                @OpenWheelMenu.performed += instance.OnOpenWheelMenu;
                @OpenWheelMenu.canceled += instance.OnOpenWheelMenu;
                @SelectOnWheelX.started += instance.OnSelectOnWheelX;
                @SelectOnWheelX.performed += instance.OnSelectOnWheelX;
                @SelectOnWheelX.canceled += instance.OnSelectOnWheelX;
                @SelectOnWheelY.started += instance.OnSelectOnWheelY;
                @SelectOnWheelY.performed += instance.OnSelectOnWheelY;
                @SelectOnWheelY.canceled += instance.OnSelectOnWheelY;
                @DeselectWeapon.started += instance.OnDeselectWeapon;
                @DeselectWeapon.performed += instance.OnDeselectWeapon;
                @DeselectWeapon.canceled += instance.OnDeselectWeapon;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @MoveAim.started += instance.OnMoveAim;
                @MoveAim.performed += instance.OnMoveAim;
                @MoveAim.canceled += instance.OnMoveAim;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @UnbalancedRight.started += instance.OnUnbalancedRight;
                @UnbalancedRight.performed += instance.OnUnbalancedRight;
                @UnbalancedRight.canceled += instance.OnUnbalancedRight;
                @UnbalancedLeft.started += instance.OnUnbalancedLeft;
                @UnbalancedLeft.performed += instance.OnUnbalancedLeft;
                @UnbalancedLeft.canceled += instance.OnUnbalancedLeft;
                @ShowPauseMenus.started += instance.OnShowPauseMenus;
                @ShowPauseMenus.performed += instance.OnShowPauseMenus;
                @ShowPauseMenus.canceled += instance.OnShowPauseMenus;
                @MenuUp.started += instance.OnMenuUp;
                @MenuUp.performed += instance.OnMenuUp;
                @MenuUp.canceled += instance.OnMenuUp;
                @MenuDown.started += instance.OnMenuDown;
                @MenuDown.performed += instance.OnMenuDown;
                @MenuDown.canceled += instance.OnMenuDown;
                @MenuLeft.started += instance.OnMenuLeft;
                @MenuLeft.performed += instance.OnMenuLeft;
                @MenuLeft.canceled += instance.OnMenuLeft;
                @MenuRight.started += instance.OnMenuRight;
                @MenuRight.performed += instance.OnMenuRight;
                @MenuRight.canceled += instance.OnMenuRight;
                @MenuTopLeft.started += instance.OnMenuTopLeft;
                @MenuTopLeft.performed += instance.OnMenuTopLeft;
                @MenuTopLeft.canceled += instance.OnMenuTopLeft;
                @MenuTopRight.started += instance.OnMenuTopRight;
                @MenuTopRight.performed += instance.OnMenuTopRight;
                @MenuTopRight.canceled += instance.OnMenuTopRight;
                @ParameterMenuPressButton.started += instance.OnParameterMenuPressButton;
                @ParameterMenuPressButton.performed += instance.OnParameterMenuPressButton;
                @ParameterMenuPressButton.canceled += instance.OnParameterMenuPressButton;
                @ClosePauseMenu.started += instance.OnClosePauseMenu;
                @ClosePauseMenu.performed += instance.OnClosePauseMenu;
                @ClosePauseMenu.canceled += instance.OnClosePauseMenu;
                @AnyButton.started += instance.OnAnyButton;
                @AnyButton.performed += instance.OnAnyButton;
                @AnyButton.canceled += instance.OnAnyButton;
                @ShowLeaveMenu.started += instance.OnShowLeaveMenu;
                @ShowLeaveMenu.performed += instance.OnShowLeaveMenu;
                @ShowLeaveMenu.canceled += instance.OnShowLeaveMenu;
            }
        }
    }
    public BoatActions @Boat => new BoatActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardMouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamePadSchemeIndex = -1;
    public InputControlScheme GamePadScheme
    {
        get
        {
            if (m_GamePadSchemeIndex == -1) m_GamePadSchemeIndex = asset.FindControlSchemeIndex("GamePad");
            return asset.controlSchemes[m_GamePadSchemeIndex];
        }
    }
    public interface IBoatActions
    {
        void OnPaddleLeft(InputAction.CallbackContext context);
        void OnPaddleRight(InputAction.CallbackContext context);
        void OnStaticRotateLeft(InputAction.CallbackContext context);
        void OnStaticRotateRight(InputAction.CallbackContext context);
        void OnResetCamera(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnDialogSkip(InputAction.CallbackContext context);
        void OnOpenWheelMenu(InputAction.CallbackContext context);
        void OnSelectOnWheelX(InputAction.CallbackContext context);
        void OnSelectOnWheelY(InputAction.CallbackContext context);
        void OnDeselectWeapon(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnMoveAim(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnUnbalancedRight(InputAction.CallbackContext context);
        void OnUnbalancedLeft(InputAction.CallbackContext context);
        void OnShowPauseMenus(InputAction.CallbackContext context);
        void OnMenuUp(InputAction.CallbackContext context);
        void OnMenuDown(InputAction.CallbackContext context);
        void OnMenuLeft(InputAction.CallbackContext context);
        void OnMenuRight(InputAction.CallbackContext context);
        void OnMenuTopLeft(InputAction.CallbackContext context);
        void OnMenuTopRight(InputAction.CallbackContext context);
        void OnParameterMenuPressButton(InputAction.CallbackContext context);
        void OnClosePauseMenu(InputAction.CallbackContext context);
        void OnAnyButton(InputAction.CallbackContext context);
        void OnShowLeaveMenu(InputAction.CallbackContext context);
    }
}
